export {default as Main } from './Main'
export {default as Login } from './Login'
export {default as Register } from './Register'
export {default as Navbar } from './Navbar'
export {default as Chat } from './Chat'
export {default as ValidationError } from './Validation-error'